version: '3.8'
services:

  postgresql_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=envoy_tutorial
      - POSTGRES_PASSWORD=rqPbqi4cRPP3JQDa
      - POSTGRES_MULTIPLE_DATABASES=coffee_db,beer_db
    ports:
      - '5432:5432'
    volumes:
      - ./Volumes/Database/Postgresql:/var/lib/postresql/data
      - ./Postgresql/:/docker-entrypoint-initdb.d
    networks:
      envoynet:
        ipv4_address: 172.20.0.2
  mongodb:
    image: mongo:5.0
    volumes:
      - ./Volumes/Database/Mongo:/data/db
    networks:
      envoynet:
        ipv4_address: 172.20.0.3
    restart: on-failure

  opensearch:
    image: "opensearchproject/opensearch:2.4.0"
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "action.auto_create_index=false"
      - "plugins.security.ssl.http.enabled=false"
      - "plugins.security.disabled=true"
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - "os_data:/usr/share/opensearch/data"
    networks:
      envoynet:
        ipv4_address: 172.20.0.4
    restart: "on-failure"

  graylog:
    hostname: "server"
    image: "${GRAYLOG_IMAGE:-graylog/graylog:5.0}"
    depends_on:
      opensearch:
        condition: "service_started"
      mongodb:
        condition: "service_started"
    entrypoint: "/usr/bin/tini -- wait-for-it opensearch:9200 --  /docker-entrypoint.sh"
    environment:
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/config/node-id"
      GRAYLOG_PASSWORD_SECRET: "${GRAYLOG_PASSWORD_SECRET:?Please configure GRAYLOG_PASSWORD_SECRET in the .env file}"
      GRAYLOG_ROOT_PASSWORD_SHA2: "${GRAYLOG_ROOT_PASSWORD_SHA2:?Please configure GRAYLOG_ROOT_PASSWORD_SHA2 in the .env file}"
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:9000/"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://opensearch:9200"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
    ports:
    - "5044:5044/tcp"   # Beats
    - "5140:5140/udp"   # Syslog
    - "5140:5140/tcp"   # Syslog
    - "5555:5555/tcp"   # RAW TCP
    - "5555:5555/udp"   # RAW TCP
    - "9000:9000/tcp"   # Server API
    - "12201:12201/tcp" # GELF TCP
    - "12201:12201/udp" # GELF UDP
    #- "10000:10000/tcp" # Custom TCP port
    #- "10000:10000/udp" # Custom UDP port
    - "13301:13301/tcp" # Forwarder data
    - "13302:13302/tcp" # Forwarder config
    volumes:
      - "graylog_data:/usr/share/graylog/data/data"
      - "graylog_journal:/usr/share/graylog/data/journal"
    networks:
      envoynet:
        ipv4_address: 172.20.0.5

  coffeeapi:
    build: CoffeeAPI/
    logging:
      driver: gelf
      options:
        gelf-address: "udp://172.20.0.5:12201"
        tag: "coffee-api"
    ports: 
      - "8080:80"
    environment:
      ASPNETCORE_URLS: "http://+"
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings_DB: Host=postgresql_db;Port=5432; Include Error Detail=True; Database=coffee_api;Username=envoy_tutorial;Password=rqPbqi4cRPP3JQDa
    depends_on:
      postgresql_db:
        condition: "service_started"
      graylog:
        condition: "service_started"
    networks:
      envoynet:
        ipv4_address: 172.20.0.6
  beerapi:
    build: BeerApi/
    logging:
      driver: gelf
      options:
        gelf-address: "udp://172.20.0.5:12201"
        tag: "beer-api"
    ports: 
      - "8081:80"
    environment:
      ASPNETCORE_URLS: "http://+"
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings_DB: Host=postgresql_db;Port=5432; Include Error Detail=True; Database=beer_api;Username=envoy_tutorial;Password=rqPbqi4cRPP3JQDa
    depends_on:
      postgresql_db:
        condition: "service_started"
      graylog:
        condition: "service_started"
    networks:
      envoynet:
        ipv4_address: 172.20.0.7
  envoygateway:
    build: Envoy/
    ports:
      - "9901:9901"
      - "10000:10000"
      - "10001:10001"
    volumes:
      - ./Envoy/envoy.yaml:/etc/envoy/envoy.yaml
      - ./Envoy/https.crt:/etc/ssl/certs/https.crt
      - ./Envoy/key.pem:/etc/ssl/certs/key.pem
    networks:
      envoynet:
        ipv4_address: 172.20.0.8

volumes:
  os_data:
  graylog_data:
  graylog_journal:

networks:
  envoynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1